#!/bin/bash/
export AZURE_OPENAI_API_KEY="YOUR_AZURE_OPENAI_API_KEY"
export AZURE_OPENAI_ENDPOINT="YOUR_AZURE_OPENAI_ENDPOINT"
export ELASTIC_CLOUD_ID="YOUR_ELASTIC_CLOUD_ID"
export ELASTIC_API_KEY="YOUR_ELASTIC_API_KEY"
export API_VERSION="YOUR_API_VERSION"
export API_EMBEDDING_DEPLOY_NAME="YOUR_API_EMBEDDING_DEPLOY_NAME"
export API_CHAT_DEPLOY_NAME="YOUR_API_CHAT_DEPLOY_NAME" 
export INDEX_NAME="YOUR_INDEX_NAME"
